Use Module:Module wikitext to tag modules
Xi-Plus/twinkle pull request #206
Opened 2021-05-07 16:05 UTC by sunny00217wm

2021-05-07 16:19 UTC, a2569875 commented
like this https://en.wikipedia.org/w/index.php?diff=978461935
if mw.config.get('wgPageContentModel') is 'Scribunto' add "require('Module:Module wikitext')._addText("{{Delete|快速刪除理由}}");'
if mw.config.get('wgPageContentModel') is 'json' ('{...}') add '"_addText":"{{Delete|快速刪除理由}}"'
if mw.config.get('wgPageContentModel') is 'json' ('[...]') add '{"_addText":"{{Delete|快速刪除理由}}"}'
if mw.config.get('wgPageContentModel') is 'js' or 'css' add '/*_addText:{{Delete|快速刪除理由}}*/'

2021-05-07 17:30 UTC, sunny00217wm commented
@a2569875 json 的改法 或許
js
if (mw.config.get('wgPageContentModel')==='json"') {
var json = JSON.parse(text)
if (json instanceof Array) {
json.unshift({_addText: code})
} else {
json._addText = code
}
text = JSON.stringify(json)
code = ''
}

2021-05-08 00:40 UTC, Xi-Plus requested changes

2021-05-08 00:40 UTC, Xi-Plus commented on package-lock.json
> +			"name": "twinkle",
不要修改無關檔案

2021-05-08 02:03 UTC, sunny00217wm commented on package-lock.json
> +			"name": "twinkle",
這就是舊版npm沒寫入，新版寫了嘛...

2021-05-08 04:57 UTC, hamishinyuu commented
其实我没看懂commit message, 啥是require delete

2021-05-08 05:02 UTC, a2569875 commented
他指的應該是request 吧

2021-05-08 05:02 UTC, hamishinyuu commented
@a2569875 ok

2021-05-09 13:30 UTC, Xi-Plus commented on modules/twinklexfd.js
> +					tag = '/* _addText: ' + tag + ' */';
對於js/css/json使用xfd通常是他人的用戶頁，但這通常沒有權限編輯，這部分程式碼沒有用處。

2021-05-09 13:31 UTC, Xi-Plus commented on modules/twinklespeedy.js
> +					}
直接replace就好，不需要indexOf。

2021-05-09 13:32 UTC, a2569875 commented on modules/twinklespeedy.js
> +					}
有用處。 見 https://zh.wikipedia.org/wiki/Template:%E6%B2%99%E7%9B%92/TemplateStyles/a2569875/SpecialWikiTextDev

2021-05-09 13:32 UTC, a2569875 commented on modules/twinklexfd.js
> +					tag = '/* _addText: ' + tag + ' */';
有用處。 見 https://zh.wikipedia.org/wiki/Template:%E6%B2%99%E7%9B%92/TemplateStyles/a2569875/SpecialWikiTextDev

2021-05-09 13:38 UTC, a2569875 commented on modules/twinklexfd.js
> +					tag = '/* _addText: ' + tag + ' */';
部分專題頁也有JSON檔

2021-05-09 13:39 UTC, Xi-Plus commented on modules/twinklexfd.js
> +					tag = '/* _addText: ' + tag + ' */';
有道理。

2021-05-10 11:35 UTC, Xi-Plus commented
重複的程式碼應該整合到一起以便後續維護，但我還在想具體該怎麼處理。

2021-05-20 04:37 UTC, Xi-Plus commented
> 重複的程式碼應該整合到一起以便後續維護，但我還在想具體該怎麼處理。

見 #215

2021-05-25 10:30 UTC, sunny00217wm commented
等待 #215 完成

2021-05-25 10:30 UTC, closed without merging