copyvio: Add copyvio-templates on non-wikitext pages [feature]
Xi-Plus/twinkle pull request #207
Opened 2021-05-08 10:58 UTC by sunny00217wm

2021-05-09 13:32 UTC, Xi-Plus commented on modules/twinklecopyvio.js
> +			return;
為什麼要獨立函數？似乎沒有必要？

2021-05-10 11:38 UTC, Xi-Plus commented
json不也需要parse嗎？不過我個人覺得parse的作法有點醜陋，把上面的subst改成safesubst就能適度的顯示模板了（只有簽名不會展開，但應可忽略）

2021-05-10 14:06 UTC, hamishinyuu requested changes

2021-05-10 14:06 UTC, hamishinyuu commented on modules/twinklecopyvio.js
> +		var tag = '{{safeubst:Copyvio/auto|url=' + params.source.replace(/http/g, '&#104;ttp').replace(/\n+/g, '\n').replace(/^\s*([^*])/gm, '* $1').replace(/^\* $/m, '') + '|OldRevision=' + mw.config.get(
safesubst

2021-05-25 10:29 UTC, closed without merging

2021-05-25 10:29 UTC, sunny00217wm commented
等待 #215 完成